treewide: Fix errors due to deprecated stuff in Clang 15.0 and above
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]